version: '3'

services:
  backend:
    image: sadanandadj/simple_app_backend:latest
    ports:
      - "5000:5000"

  frontend:
    image: sadanandadj/simple_app_frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
